version: "3.7"
services:
  app_curso_api:
    build:
      args:
        user: miguel
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: app_curso_api
    container_name: app_curso_api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./curso-api:/var/www/html
    networks:
      - netcursoapi

  db_curso_api:
    image: mysql:8.0
    container_name: db_curso_api
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: curso_api
      MYSQL_ROOT_PASSWORD: miguelmav
      MYSQL_PASSWORD: miguel
      MYSQL_USER: miguel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3367:3306
    volumes:
      - ./mysqldb:/var/lib/mysql
    networks:
      - netcursoapi

  nginx_curso_api:
    image: nginx:alpine
    container_name: nginx_curso_api
    restart: unless-stopped
    ports:
      - 6001:80
    volumes:
      - ./curso-api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netcursoapi

networks:
  netcursoapi:
    driver: bridge
